# infra/docker-compose.dev.yml (最终修正版)
services:
  cloudsql:
    image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.13.0
    command:
      - "--port=5432"
      - "${CLOUD_SQL_CONN_NAME}"
    volumes:
      - ../.gcp/dev-sa-key.json:/config/sa.json:ro
    environment:
      - "GOOGLE_APPLICATION_CREDENTIALS=/config/sa.json"
    env_file:
      - ../.env # 确保代理也能读取到变量

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  api:
    build:
      context: ..
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    depends_on:
      - cloudsql
      - redis
    volumes:
      - ../.gcp/dev-sa-key.json:/app/.gcp/dev-sa.json:ro

  worker:
    build:
      context: ..
      dockerfile: Dockerfile.worker
    # 关键修正：明确指定启动命令，使用虚拟环境中的celery
    command: /opt/venv/bin/celery -A services.api.app.core.celery_app:celery_app worker -l info -Q default,cpu_queue,analysis_queue,api_queue,gpu_queue
    env_file:
      - ../.env
    depends_on:
      - cloudsql
      - redis
    volumes:
      - ../.gcp/dev-sa-key.json:/app/.gcp/dev-sa.json:ro

  flower:
    image: mher/flower
    # 关键修正：Flower也需要知道broker的地址
    command: --broker=${CELERY_BROKER_URL}
    ports:
      - "5555:5555"
    env_file:
      - ../.env
    depends_on:
      - redis