services:
  api:
    image: ghcr.io/<你的owner或用户名>/yvideo-factory:${IMAGE_TAG}
    env_file:
      - ../.env.prod
    ports:
      - "8000:8000"
    volumes:
      - ../dev_outputs:/app/services/api/app/data
      - ../prompts:/app/prompts
      - ../rules:/app/rules
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
    restart: unless-stopped

