# infra/docker-compose.prod.yml
version: '3.8'

services:
  worker:
    # 修改：更新了镜像的完整路径，包含仓库名称'videofactory-repo'
    image: us-central1-docker.pkg.dev/fleet-blend-469520-n7/videofactory-repo/worker:latest
    command: celery -A services.api.app.core.celery_app:celery_app worker -l info
    env_file:
      - .env.prod
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
