services:
  api:
    build:
      context: ..
      dockerfile: Dockerfile.api
    env_file:
      - ../.env
    ports:
      - "8000:8000"
    volumes:
      - ../services/api/app:/app/services/api/app          # 代码热更新
      - ../dev_outputs:/app/services/api/app/data          # 输出目录 → /data 静态挂载
      - ../prompts:/app/prompts                            # ★ Prompt 热更新
      - ../rules:/app/rules                                # ★ 规则热更新
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
    restart: unless-stopped

