services:
  api:
    build:
      context: ..
      dockerfile: Dockerfile.api
    env_file:
      - ../.env
    ports:
      - "8000:8000"
    volumes:
      - ../services/api/app:/app/services/api/app
      - ../dev_outputs:/app/services/api/app/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
    restart: unless-stopped
