# infra/docker-compose.dev.yml (最终修正版 V4)
services:
  cloudsql:
    image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.8.0
    command:
      - "--port=5432"
      - "${CLOUD_SQL_CONN_NAME}"
    # 关键修正 1: 将本地的密钥文件直接挂载到容器内的一个特定路径，例如 /secrets/sa.json
    volumes:
      - ../.gcp/dev-sa-key.json:/secrets/sa.json:ro
    environment:
      # 关键修正 2: GOOGLE_APPLICATION_CREDENTIALS 必须精确指向挂载后的文件路径
      - "GOOGLE_APPLICATION_CREDENTIALS=/secrets/sa.json"
    env_file:
      - ../.env
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 5432"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  api:
    build:
      context: ..
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    depends_on:
      cloudsql:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - ../.gcp:/app/.gcp:ro

  worker:
    build:
      context: ..
      dockerfile: Dockerfile.worker
    command: /opt/venv/bin/celery -A services.api.app.core.celery_app:celery_app worker -l info
    env_file:
      - ../.env
    depends_on:
      cloudsql:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - ../.gcp:/app/.gcp:ro

  flower:
    image: mher/flower
    # 关键修正 3: 使用正确的列表格式 (exec form) 来定义命令和参数
    command: 
      - "celery"
      - "-A"
      - "services.api.app.core.celery_app:celery_app"
      - "flower"
      - "--broker=${CELERY_BROKER_URL}"
    ports:
      - "5555:5555"
    env_file:
      - ../.env
    depends_on:
      - redis