# infra/docker-compose.dev.yml (最终修正版 V2)
services:
  cloudsql:
    image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.13.0
    command:
      - "--port=5432"
      - "--address=0.0.0.0"
      - "${CLOUD_SQL_CONN_NAME}"
    volumes:
      - ../.gcp/dev-sa-key.json:/config:ro
    environment:
      - "GOOGLE_APPLICATION_CREDENTIALS=/config"
    env_file:
      - ../.env
    # 关键修正 1: 增加健康检查，确保代理完全可用
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 5432"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  api:
    build:
      context: ..
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    depends_on:
      # 关键修正 2: 让API服务等待cloudsql健康后再启动
      cloudsql:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - ../.gcp:/app/.gcp:ro

  worker:
    build:
      context: ..
      dockerfile: Dockerfile.worker
    command: /opt/venv/bin/celery -A services.api.app.core.celery_app:celery_app worker -l info
    user: "1000:1000" # 避免权限问题
    env_file:
      - ../.env
    depends_on:
      # 关键修正 3: 让Worker服务也等待cloudsql健康后再启动
      cloudsql:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - ../.gcp:/app/.gcp:ro

  flower:
    image: mher/flower
    # 关键修正: 将 command 指令修改为列表格式 (exec form)
    command: 
      - "celery"
      - "--broker=${CELERY_BROKER_URL}"
      - "flower"
    ports:
      - "5555:5555"
    env_file:
      - ../.env
    depends_on:
      - redis
      - worker
    restart: unless-stopped